In [1]:
import pandas as pd
import numpy as np

In [2]:
file = 'test.csv'
df = pd.read_csv(file)
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities      ...       ScreenPorch PoolArea PoolQC  Fence  \
0         Lvl    AllPub      ...               120        0    NaN  MnPrv   
1         Lvl    AllPub      ...                 0        0    NaN    NaN   
2         Lvl    AllPub      ...                 0        0    NaN  MnPrv   
3         Lvl    AllPub      ...                 0        0    NaN    NaN   
4         HLS    AllPub      ...               144        0    NaN    NaN   

  MiscFeature MiscVal MoSold  YrSold  SaleType  SaleCondition  
0         NaN       0      6    2010        WD         Normal  
1        Gar2   12500      6    2010        WD         Normal  
2         NaN       0      3    2010        WD         Normal  
3         NaN       0      6    2010        WD         Normal  
4         NaN       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null object
LotFrontage      1232 non-null float64
LotArea          1459 non-null int64
Street           1459 non-null object
Alley            107 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
OverallQual      1459 non-null int64
OverallCond      1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-

In [4]:
df_copy = df.copy()

## Diccionario `dict_MSZoning`

In [5]:
column = 'MSZoning'

In [6]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0       RH
1       RL
2       RM
3       FV
4  C (all)

In [7]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [8]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [9]:
grouped.shape

(5, 2)

In [10]:
grouped['index'] += 1
grouped

index      Key
0      1       RH
1      2       RL
2      3       RM
3      4       FV
4      5  C (all)

In [11]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [12]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'RH'], [2, 'RL'], [3, 'RM'], [4, 'FV'], [5, 'C (all)']]}

In [13]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'RH': 1, 'RL': 2, 'RM': 3, 'FV': 4, 'C (all)': 5}

In [14]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

ValueError: Cannot convert non-finite values (NA or inf) to integer

## Diccionario `Street`

In [ ]:
column = 'Street'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `LotShape`

In [ ]:
column = 'LotShape'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `LandContour`

In [ ]:
column = 'LandContour'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Utilities`

In [ ]:
column = 'Utilities'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `LotConfig`

In [ ]:
column = 'LotConfig'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `LandSlope`

In [ ]:
column = 'LandSlope'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Neighborhood`

In [ ]:
column = 'Neighborhood'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Condition1`

In [ ]:
column = 'Condition1'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Condition2`

In [ ]:
column = 'Condition2'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `BldgType`

In [ ]:
column = 'BldgType'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `HouseStyle`

In [ ]:
column = 'HouseStyle'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `RoofStyle`

In [ ]:
column = 'RoofStyle'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `RoofMatl`

In [ ]:
column = 'RoofMatl'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Exterior1st`

In [ ]:
column = 'Exterior1st'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Exterior2nd`

In [ ]:
column = 'Exterior2nd'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `MasVnrType`

In [ ]:
column = 'MasVnrType'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `ExterQual`

In [ ]:
column = 'ExterQual'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `ExterCond`

In [ ]:
column = 'ExterCond'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `Foundation`

In [ ]:
column = 'Foundation'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `BsmtQual`

In [ ]:
column = 'BsmtQual'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `BsmtCond`

In [ ]:
column = 'BsmtCond'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [ ]:
grouped.reset_index(inplace=True)
grouped.columns

In [ ]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

In [ ]:
grouped.shape

In [ ]:
grouped['index'] += 1
grouped

In [ ]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

In [ ]:
dict_.pop('index')
dict_.pop('columns')
dict_

In [ ]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

In [ ]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

## Diccionario `BsmtExposure`

In [ ]:
column = 'BsmtExposure'

In [ ]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

In [15]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['level_0', 'index', 'Key'], dtype='object')

In [16]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['level_0', 'index', 'Key'], dtype='object')

In [17]:
grouped.shape

(5, 3)

In [18]:
grouped['index'] += 1
grouped

level_0  index      Key
0        0      2       RH
1        1      3       RL
2        2      4       RM
3        3      5       FV
4        4      6  C (all)

In [19]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [20]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[0, 2, 'RH'],
  [1, 3, 'RL'],
  [2, 4, 'RM'],
  [3, 5, 'FV'],
  [4, 6, 'C (all)']]}

In [21]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{2: 0, 3: 1, 4: 2, 5: 3, 6: 4}

In [22]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  0.,  2.,  3., nan])

## Diccionario `BsmtFinType1`

In [23]:
column = 'BsmtFinType1'

In [24]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Rec
1  ALQ
2  GLQ
3  Unf
4  BLQ

In [25]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [26]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [27]:
grouped.shape

(6, 2)

In [28]:
grouped['index'] += 1
grouped

index  Key
0      1  Rec
1      2  ALQ
2      3  GLQ
3      4  Unf
4      5  BLQ
5      6  LwQ

In [29]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [30]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Rec'],
  [2, 'ALQ'],
  [3, 'GLQ'],
  [4, 'Unf'],
  [5, 'BLQ'],
  [6, 'LwQ']]}

In [31]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Rec': 1, 'ALQ': 2, 'GLQ': 3, 'Unf': 4, 'BLQ': 5, 'LwQ': 6}

In [32]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6., nan])

## Diccionario `BsmtFinType2`

In [33]:
column = 'BsmtFinType2'

In [34]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  LwQ
1  Unf
2  Rec
3  BLQ
4  GLQ

In [35]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [36]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [37]:
grouped.shape

(6, 2)

In [38]:
grouped['index'] += 1
grouped

index  Key
0      1  LwQ
1      2  Unf
2      3  Rec
3      4  BLQ
4      5  GLQ
5      6  ALQ

In [39]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [40]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'LwQ'],
  [2, 'Unf'],
  [3, 'Rec'],
  [4, 'BLQ'],
  [5, 'GLQ'],
  [6, 'ALQ']]}

In [41]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'LwQ': 1, 'Unf': 2, 'Rec': 3, 'BLQ': 4, 'GLQ': 5, 'ALQ': 6}

In [42]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6., nan])

## Diccionario `Heating`

In [43]:
column = 'Heating'

In [44]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  GasA
1  GasW
2  Grav
3  Wall

In [45]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [46]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [47]:
grouped.shape

(4, 2)

In [48]:
grouped['index'] += 1
grouped

index   Key
0      1  GasA
1      2  GasW
2      3  Grav
3      4  Wall

In [49]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [50]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'GasA'], [2, 'GasW'], [3, 'Grav'], [4, 'Wall']]}

In [51]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'GasA': 1, 'GasW': 2, 'Grav': 3, 'Wall': 4}

In [52]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `HeatingQC`

In [53]:
column = 'HeatingQC'

In [54]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Ex
3  Fa
4  Po

In [55]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [56]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [57]:
grouped.shape

(5, 2)

In [58]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Ex
3      4  Fa
4      5  Po

In [59]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [60]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Ex'], [4, 'Fa'], [5, 'Po']]}

In [61]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Ex': 3, 'Fa': 4, 'Po': 5}

In [62]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `CentralAir`

In [63]:
column = 'CentralAir'

In [64]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Y
1  N

In [65]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [66]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [67]:
grouped.shape

(2, 2)

In [68]:
grouped['index'] += 1
grouped

index Key
0      1   Y
1      2   N

In [69]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [70]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Y'], [2, 'N']]}

In [71]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Y': 1, 'N': 2}

In [72]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2])

## Diccionario `Electrical`

In [73]:
column = 'Electrical'

In [74]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  SBrkr
1  FuseA
2  FuseF
3  FuseP

In [75]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [76]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [77]:
grouped.shape

(4, 2)

In [78]:
grouped['index'] += 1
grouped

index    Key
0      1  SBrkr
1      2  FuseA
2      3  FuseF
3      4  FuseP

In [79]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [80]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'SBrkr'], [2, 'FuseA'], [3, 'FuseF'], [4, 'FuseP']]}

In [81]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'SBrkr': 1, 'FuseA': 2, 'FuseF': 3, 'FuseP': 4}

In [82]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `KitchenQual`

In [83]:
column = 'KitchenQual'

In [84]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Ex
3  Fa

In [85]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [86]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [87]:
grouped.shape

(4, 2)

In [88]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Ex
3      4  Fa

In [89]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [90]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Ex'], [4, 'Fa']]}

In [91]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Ex': 3, 'Fa': 4}

In [92]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4., nan])

## Diccionario `Functional`

In [93]:
column = 'Functional'

In [94]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Typ
1  Min2
2  Min1
3   Mod
4  Maj1

In [95]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [96]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [97]:
grouped.shape

(7, 2)

In [98]:
grouped['index'] += 1
grouped

index   Key
0      1   Typ
1      2  Min2
2      3  Min1
3      4   Mod
4      5  Maj1
5      6   Sev
6      7  Maj2

In [99]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [100]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Typ'],
  [2, 'Min2'],
  [3, 'Min1'],
  [4, 'Mod'],
  [5, 'Maj1'],
  [6, 'Sev'],
  [7, 'Maj2']]}

In [101]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Typ': 1, 'Min2': 2, 'Min1': 3, 'Mod': 4, 'Maj1': 5, 'Sev': 6, 'Maj2': 7}

In [102]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

## Diccionario `FireplaceQu`

In [103]:
column = 'FireplaceQu'

In [104]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Po
3  Fa
4  Ex

In [105]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [106]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [107]:
grouped.shape

(5, 2)

In [108]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Po
3      4  Fa
4      5  Ex

In [109]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [110]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Po'], [4, 'Fa'], [5, 'Ex']]}

In [111]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Po': 3, 'Fa': 4, 'Ex': 5}

In [112]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([nan,  1.,  2.,  3.,  4.,  5.])

## Diccionario `GarageType`

In [113]:
column = 'GarageType'

In [114]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Attchd
1   Detchd
2  BuiltIn
3  Basment
4   2Types

In [115]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [116]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [117]:
grouped.shape

(6, 2)

In [118]:
grouped['index'] += 1
grouped

index      Key
0      1   Attchd
1      2   Detchd
2      3  BuiltIn
3      4  Basment
4      5   2Types
5      6  CarPort

In [119]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [120]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Attchd'],
  [2, 'Detchd'],
  [3, 'BuiltIn'],
  [4, 'Basment'],
  [5, '2Types'],
  [6, 'CarPort']]}

In [121]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Attchd': 1,
 'Detchd': 2,
 'BuiltIn': 3,
 'Basment': 4,
 '2Types': 5,
 'CarPort': 6}

In [122]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3., nan,  4.,  5.,  6.])

## Diccionario `GarageFinish`

In [123]:
column = 'GarageFinish'

In [124]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Unf
1  Fin
2  RFn

In [125]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [126]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [127]:
grouped.shape

(3, 2)

In [128]:
grouped['index'] += 1
grouped

index  Key
0      1  Unf
1      2  Fin
2      3  RFn

In [129]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [130]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Unf'], [2, 'Fin'], [3, 'RFn']]}

In [131]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Unf': 1, 'Fin': 2, 'RFn': 3}

In [132]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3., nan])

## Diccionario `GarageQual`

In [133]:
column = 'GarageQual'

In [134]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Fa
2  Gd
3  Po

In [135]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [136]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [137]:
grouped.shape

(4, 2)

In [138]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Fa
2      3  Gd
3      4  Po

In [139]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [140]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Fa'], [3, 'Gd'], [4, 'Po']]}

In [141]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Fa': 2, 'Gd': 3, 'Po': 4}

In [142]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1., nan,  2.,  3.,  4.])

## Diccionario `GarageCond`

In [143]:
column = 'GarageCond'

In [144]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Fa
2  Gd
3  Po
4  Ex

In [145]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [146]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [147]:
grouped.shape

(5, 2)

In [148]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Fa
2      3  Gd
3      4  Po
4      5  Ex

In [149]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [150]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Fa'], [3, 'Gd'], [4, 'Po'], [5, 'Ex']]}

In [151]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Fa': 2, 'Gd': 3, 'Po': 4, 'Ex': 5}

In [152]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1., nan,  2.,  3.,  4.,  5.])

## Diccionario `GarageYrBlt`

In [153]:
column = 'GarageYrBlt'

In [154]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped = grouped.astype('int64')
grouped.head()

0
0  1961
1  1958
2  1997
3  1998
4  1992

In [155]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [156]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [157]:
grouped.shape

(97, 2)

In [158]:
grouped['index'] += 1
grouped

index   Key
0       1  1961
1       2  1958
2       3  1997
3       4  1998
4       5  1992
5       6  1993
6       7  1990
7       8  1970
8       9  1999
9      10  1971
10     11  1975
11     12  2009
12     13  2005
13     14  2003
14     15  2002
15     16  2006
16     17  2004
17     18  1920
18     19  1974
19     20  2000
20     21  2010
21     22  1967
22     23  1978
23     24  1966
24     25  1964
25     26  1994
26     27  1949
27     28  1959
28     29  1956
29     30  1952
..    ...   ...
67     68  1972
68     69  1984
69     70  1985
70     71  1996
71     72  1995
72     73  1980
73     74  1986
74     75  1981
75     76  1982
76     77  1991
77     78  1988
78     79  1953
79     80  1924
80     81  1927
81     82  1946
82     83  1934
83     84  1983
84     85  1916
85     86  1918
86     87  1937
87     88  1932
88     89  1935
89     90  1925
90     91  1921
91     92  1895
92     93  1922
93     94  2207
94     95  1936
95     96  1943
96     97  1919

[97 rows x 2 columns]

In [159]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [160]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 1961],
  [2, 1958],
  [3, 1997],
  [4, 1998],
  [5, 1992],
  [6, 1993],
  [7, 1990],
  [8, 1970],
  [9, 1999],
  [10, 1971],
  [11, 1975],
  [12, 2009],
  [13, 2005],
  [14, 2003],
  [15, 2002],
  [16, 2006],
  [17, 2004],
  [18, 1920],
  [19, 1974],
  [20, 2000],
  [21, 2010],
  [22, 1967],
  [23, 1978],
  [24, 1966],
  [25, 1964],
  [26, 1994],
  [27, 1949],
  [28, 1959],
  [29, 1956],
  [30, 1952],
  [31, 1955],
  [32, 1989],
  [33, 1950],
  [34, 1960],
  [35, 1963],
  [36, 1900],
  [37, 1957],
  [38, 1938],
  [39, 1948],
  [40, 1962],
  [41, 1928],
  [42, 1930],
  [43, 1926],
  [44, 1939],
  [45, 1973],
  [46, 1942],
  [47, 1979],
  [48, 1923],
  [49, 1915],
  [50, 1917],
  [51, 1940],
  [52, 1910],
  [53, 1969],
  [54, 1968],
  [55, 1977],
  [56, 1945],
  [57, 1987],
  [58, 1947],
  [59, 1954],
  [60, 1941],
  [61, 1951],
  [62, 1896],
  [63, 1976],
  [64, 2008],
  [65, 2007],
  [66, 1965],
  [67, 2001],
  [68, 1972],
  [69, 1984],
  [70, 1985],
  [71, 1996],
  [72, 

In [161]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{1961: 1,
 1958: 2,
 1997: 3,
 1998: 4,
 1992: 5,
 1993: 6,
 1990: 7,
 1970: 8,
 1999: 9,
 1971: 10,
 1975: 11,
 2009: 12,
 2005: 13,
 2003: 14,
 2002: 15,
 2006: 16,
 2004: 17,
 1920: 18,
 1974: 19,
 2000: 20,
 2010: 21,
 1967: 22,
 1978: 23,
 1966: 24,
 1964: 25,
 1994: 26,
 1949: 27,
 1959: 28,
 1956: 29,
 1952: 30,
 1955: 31,
 1989: 32,
 1950: 33,
 1960: 34,
 1963: 35,
 1900: 36,
 1957: 37,
 1938: 38,
 1948: 39,
 1962: 40,
 1928: 41,
 1930: 42,
 1926: 43,
 1939: 44,
 1973: 45,
 1942: 46,
 1979: 47,
 1923: 48,
 1915: 49,
 1917: 50,
 1940: 51,
 1910: 52,
 1969: 53,
 1968: 54,
 1977: 55,
 1945: 56,
 1987: 57,
 1947: 58,
 1954: 59,
 1941: 60,
 1951: 61,
 1896: 62,
 1976: 63,
 2008: 64,
 2007: 65,
 1965: 66,
 2001: 67,
 1972: 68,
 1984: 69,
 1985: 70,
 1996: 71,
 1995: 72,
 1980: 73,
 1986: 74,
 1981: 75,
 1982: 76,
 1991: 77,
 1988: 78,
 1953: 79,
 1924: 80,
 1927: 81,
 1946: 82,
 1934: 83,
 1983: 84,
 1916: 85,
 1918: 86,
 1937: 87,
 1932: 88,
 1935: 89,
 1925: 90,
 1921: 91,
 1895: 9

In [162]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., nan,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97.])

## Diccionario `PavedDrive`

In [163]:
column = 'PavedDrive'

In [164]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Y
1  N
2  P

In [165]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [166]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [167]:
grouped.shape

(3, 2)

In [168]:
grouped['index'] += 1
grouped

index Key
0      1   Y
1      2   N
2      3   P

In [169]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [170]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Y'], [2, 'N'], [3, 'P']]}

In [171]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Y': 1, 'N': 2, 'P': 3}

In [172]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3])

## Diccionario `SaleType`

In [173]:
column = 'SaleType'

In [174]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0     WD
1    COD
2    New
3  ConLD
4    Oth

In [175]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [176]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [177]:
grouped.shape

(9, 2)

In [178]:
grouped['index'] += 1
grouped

index    Key
0      1     WD
1      2    COD
2      3    New
3      4  ConLD
4      5    Oth
5      6    Con
6      7  ConLw
7      8  ConLI
8      9    CWD

In [179]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [180]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'WD'],
  [2, 'COD'],
  [3, 'New'],
  [4, 'ConLD'],
  [5, 'Oth'],
  [6, 'Con'],
  [7, 'ConLw'],
  [8, 'ConLI'],
  [9, 'CWD']]}

In [181]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'WD': 1,
 'COD': 2,
 'New': 3,
 'ConLD': 4,
 'Oth': 5,
 'Con': 6,
 'ConLw': 7,
 'ConLI': 8,
 'CWD': 9}

In [182]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., nan])

## Diccionario `SaleCondition`

In [183]:
column = 'SaleCondition'

In [184]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Normal
1  Partial
2  Abnorml
3   Family
4   Alloca

In [185]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [186]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [187]:
grouped.shape

(6, 2)

In [188]:
grouped['index'] += 1
grouped

index      Key
0      1   Normal
1      2  Partial
2      3  Abnorml
3      4   Family
4      5   Alloca
5      6  AdjLand

In [189]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [190]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Normal'],
  [2, 'Partial'],
  [3, 'Abnorml'],
  [4, 'Family'],
  [5, 'Alloca'],
  [6, 'AdjLand']]}

In [191]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Normal': 1,
 'Partial': 2,
 'Abnorml': 3,
 'Family': 4,
 'Alloca': 5,
 'AdjLand': 6}

In [192]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6])

In [193]:
for line in df_copy.columns:
    print(line, ' : ', df_copy[line].unique(), '\n')

Id  :  [1461 1462 1463 ... 2917 2918 2919] 

MSSubClass  :  [ 20  60 120 160  80  30  50  90  85 190  45  70  75 180  40 150] 

MSZoning  :  [ 1.  0.  2.  3. nan] 

LotFrontage  :  [ 80.  81.  74.  78.  43.  75.  nan  63.  85.  70.  26.  21.  24. 102.
  94.  90.  79. 110. 105.  41. 100.  67.  60.  73.  92.  84.  39.  88.
  25.  30.  57.  68.  98. 120.  87. 119.  65.  56.  69.  50.  53.  52.
  51.  72.  86. 124.  44.  83.  64.  82.  38.  89.  35.  58.  66.  93.
  31.  76.  28.  61.  95. 129.  59.  77.  96.  47.  34. 117.  48.  62.
  42. 106. 112.  32. 115.  71.  45. 109. 113. 125. 101. 104. 108. 130.
 135.  36.  55. 136.  97.  91.  37.  22. 103.  99.  40. 123.  54. 107.
 150. 160. 195. 128.  33. 118. 134. 155. 126.  46. 149. 200. 121. 131.
 114.  49. 133. 140.] 

LotArea  :  [11622 14267 13830 ...  1894 20000 10441] 

Street  :  ['Pave' 'Grvl'] 

Alley  :  [nan 'Pave' 'Grvl'] 

LotShape  :  ['Reg' 'IR1' 'IR2' 'IR3'] 

LandContour  :  ['Lvl' 'HLS' 'Bnk' 'Low'] 

Utilities  :  ['AllPub' n

In [194]:
import math
print(math.nan)

nan


In [195]:
import numpy as np
np.NaN

nan

## NaN

In [196]:
df_copy.fillna(value=-1, inplace=True)

In [197]:
n = df_copy.columns.values.tolist()
m = round(df_copy.shape[0]*.80)

l = []
for i in n:
    print(i)
    if df_copy[i].value_counts().get(-1) != None:
#        print(m, " < ", df_copy[i].value_counts().get(-1))
        if m < df_copy[i].value_counts().get(-1):
            print(i)
            l.append(i)
            df_copy.drop(labels=i, axis=1, inplace=True)

Id
MSSubClass
MSZoning
LotFrontage
LotArea
Street
Alley
Alley
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
OverallQual
OverallCond
YearBuilt
YearRemodAdd
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
MasVnrArea
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtFinType2
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
Heating
HeatingQC
CentralAir
Electrical
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
KitchenQual
TotRmsAbvGrd
Functional
Fireplaces
FireplaceQu
GarageType
GarageYrBlt
GarageFinish
GarageCars
GarageArea
GarageQual
GarageCond
PavedDrive
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
PoolQC
PoolQC
Fence
Fence
MiscFeature
MiscFeature
MiscVal
MoSold
YrSold
SaleType
SaleCondition


In [198]:
df_copy.replace(to_replace= -1, value=np.NaN, inplace=True)

In [199]:
df_copy.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea Street LotShape  \
0  1461          20       1.0         80.0    11622   Pave      Reg   
1  1462          20       0.0         81.0    14267   Pave      IR1   
2  1463          60       0.0         74.0    13830   Pave      IR1   
3  1464          60       0.0         78.0     9978   Pave      IR1   
4  1465         120       0.0         43.0     5005   Pave      IR1   

  LandContour Utilities LotConfig      ...       OpenPorchSF EnclosedPorch  \
0         Lvl    AllPub    Inside      ...                 0             0   
1         Lvl    AllPub    Corner      ...                36             0   
2         Lvl    AllPub    Inside      ...                34             0   
3         Lvl    AllPub    Inside      ...                36             0   
4         HLS    AllPub    Inside      ...                82             0   

  3SsnPorch ScreenPorch PoolArea MiscVal  MoSold  YrSold  SaleType  \
0         0         120        0       0       6    2010       1.0   
1         0           0        0   12500       6    2010       1.0   
2         0           0        0       0       3    2010       1.0   
3         0           0        0       0       6    2010       1.0   
4         0         144        0       0       1    2010       1.0   

   SaleCondition  
0              1  
1              1  
2              1  
3              1  
4              1  

[5 rows x 76 columns]

In [200]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 76 columns):
Id               1459 non-null int64
MSSubClass       1459 non-null int64
MSZoning         1455 non-null float64
LotFrontage      1232 non-null float64
LotArea          1459 non-null int64
Street           1459 non-null object
LotShape         1459 non-null object
LandContour      1459 non-null object
Utilities        1457 non-null object
LotConfig        1459 non-null object
LandSlope        1459 non-null object
Neighborhood     1459 non-null object
Condition1       1459 non-null object
Condition2       1459 non-null object
BldgType         1459 non-null object
HouseStyle       1459 non-null object
OverallQual      1459 non-null int64
OverallCond      1459 non-null int64
YearBuilt        1459 non-null int64
YearRemodAdd     1459 non-null int64
RoofStyle        1459 non-null object
RoofMatl         1459 non-null object
Exterior1st      1458 non-null object
Exterior2nd      1458 no

In [201]:
df_copy.to_csv('test_clean.csv')