In [1664]:
import pandas as pd
import numpy as np

In [1665]:
file = 'train.csv'
df = pd.read_csv(file)
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [1666]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-n

In [1667]:
df_copy = df.copy()

## Diccionario `dict_MSZoning`

In [1668]:
column = 'MSZoning'

In [1669]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0       RL
1       RM
2  C (all)
3       FV
4       RH

In [1670]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1671]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1672]:
grouped.shape

(5, 2)

In [1673]:
grouped['index'] += 1
grouped

index      Key
0      1       RL
1      2       RM
2      3  C (all)
3      4       FV
4      5       RH

In [1674]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1675]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'RL'], [2, 'RM'], [3, 'C (all)'], [4, 'FV'], [5, 'RH']]}

In [1676]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'RL': 1, 'RM': 2, 'C (all)': 3, 'FV': 4, 'RH': 5}

In [1677]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `Street`

In [1678]:
column = 'Street'

In [1679]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Pave
1  Grvl

In [1680]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1681]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1682]:
grouped.shape

(2, 2)

In [1683]:
grouped['index'] += 1
grouped

index   Key
0      1  Pave
1      2  Grvl

In [1684]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1685]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Pave'], [2, 'Grvl']]}

In [1686]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Pave': 1, 'Grvl': 2}

In [1687]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2])

## Diccionario `LotShape`

In [1688]:
column = 'LotShape'

In [1689]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Reg
1  IR1
2  IR2
3  IR3

In [1690]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1691]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1692]:
grouped.shape

(4, 2)

In [1693]:
grouped['index'] += 1
grouped

index  Key
0      1  Reg
1      2  IR1
2      3  IR2
3      4  IR3

In [1694]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1695]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Reg'], [2, 'IR1'], [3, 'IR2'], [4, 'IR3']]}

In [1696]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Reg': 1, 'IR1': 2, 'IR2': 3, 'IR3': 4}

In [1697]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `LandContour`

In [1698]:
column = 'LandContour'

In [1699]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Lvl
1  Bnk
2  Low
3  HLS

In [1700]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1701]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1702]:
grouped.shape

(4, 2)

In [1703]:
grouped['index'] += 1
grouped

index  Key
0      1  Lvl
1      2  Bnk
2      3  Low
3      4  HLS

In [1704]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1705]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Lvl'], [2, 'Bnk'], [3, 'Low'], [4, 'HLS']]}

In [1706]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Lvl': 1, 'Bnk': 2, 'Low': 3, 'HLS': 4}

In [1707]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `Utilities`

In [1708]:
column = 'Utilities'

In [1709]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  AllPub
1  NoSeWa

In [1710]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1711]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1712]:
grouped.shape

(2, 2)

In [1713]:
grouped['index'] += 1
grouped

index     Key
0      1  AllPub
1      2  NoSeWa

In [1714]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1715]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'AllPub'], [2, 'NoSeWa']]}

In [1716]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'AllPub': 1, 'NoSeWa': 2}

In [1717]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2])

## Diccionario `LotConfig`

In [1718]:
column = 'LotConfig'

In [1719]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Inside
1      FR2
2   Corner
3  CulDSac
4      FR3

In [1720]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1721]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1722]:
grouped.shape

(5, 2)

In [1723]:
grouped['index'] += 1
grouped

index      Key
0      1   Inside
1      2      FR2
2      3   Corner
3      4  CulDSac
4      5      FR3

In [1724]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1725]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Inside'],
  [2, 'FR2'],
  [3, 'Corner'],
  [4, 'CulDSac'],
  [5, 'FR3']]}

In [1726]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Inside': 1, 'FR2': 2, 'Corner': 3, 'CulDSac': 4, 'FR3': 5}

In [1727]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `LandSlope`

In [1728]:
column = 'LandSlope'

In [1729]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Gtl
1  Mod
2  Sev

In [1730]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1731]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1732]:
grouped.shape

(3, 2)

In [1733]:
grouped['index'] += 1
grouped

index  Key
0      1  Gtl
1      2  Mod
2      3  Sev

In [1734]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1735]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Gtl'], [2, 'Mod'], [3, 'Sev']]}

In [1736]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Gtl': 1, 'Mod': 2, 'Sev': 3}

In [1737]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3])

## Diccionario `Neighborhood`

In [1738]:
column = 'Neighborhood'

In [1739]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  CollgCr
1  Veenker
2  Crawfor
3  NoRidge
4  Mitchel

In [1740]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1741]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1742]:
grouped.shape

(25, 2)

In [1743]:
grouped['index'] += 1
grouped

index      Key
0       1  CollgCr
1       2  Veenker
2       3  Crawfor
3       4  NoRidge
4       5  Mitchel
5       6  Somerst
6       7   NWAmes
7       8  OldTown
8       9  BrkSide
9      10   Sawyer
10     11  NridgHt
11     12    NAmes
12     13  SawyerW
13     14   IDOTRR
14     15  MeadowV
15     16  Edwards
16     17   Timber
17     18  Gilbert
18     19  StoneBr
19     20  ClearCr
20     21  NPkVill
21     22  Blmngtn
22     23   BrDale
23     24    SWISU
24     25  Blueste

In [1744]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1745]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'CollgCr'],
  [2, 'Veenker'],
  [3, 'Crawfor'],
  [4, 'NoRidge'],
  [5, 'Mitchel'],
  [6, 'Somerst'],
  [7, 'NWAmes'],
  [8, 'OldTown'],
  [9, 'BrkSide'],
  [10, 'Sawyer'],
  [11, 'NridgHt'],
  [12, 'NAmes'],
  [13, 'SawyerW'],
  [14, 'IDOTRR'],
  [15, 'MeadowV'],
  [16, 'Edwards'],
  [17, 'Timber'],
  [18, 'Gilbert'],
  [19, 'StoneBr'],
  [20, 'ClearCr'],
  [21, 'NPkVill'],
  [22, 'Blmngtn'],
  [23, 'BrDale'],
  [24, 'SWISU'],
  [25, 'Blueste']]}

In [1746]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'CollgCr': 1,
 'Veenker': 2,
 'Crawfor': 3,
 'NoRidge': 4,
 'Mitchel': 5,
 'Somerst': 6,
 'NWAmes': 7,
 'OldTown': 8,
 'BrkSide': 9,
 'Sawyer': 10,
 'NridgHt': 11,
 'NAmes': 12,
 'SawyerW': 13,
 'IDOTRR': 14,
 'MeadowV': 15,
 'Edwards': 16,
 'Timber': 17,
 'Gilbert': 18,
 'StoneBr': 19,
 'ClearCr': 20,
 'NPkVill': 21,
 'Blmngtn': 22,
 'BrDale': 23,
 'SWISU': 24,
 'Blueste': 25}

In [1747]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

## Diccionario `Condition1`

In [1748]:
column = 'Condition1'

In [1749]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0    Norm
1   Feedr
2    PosN
3  Artery
4    RRAe

In [1750]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1751]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1752]:
grouped.shape

(9, 2)

In [1753]:
grouped['index'] += 1
grouped

index     Key
0      1    Norm
1      2   Feedr
2      3    PosN
3      4  Artery
4      5    RRAe
5      6    RRNn
6      7    RRAn
7      8    PosA
8      9    RRNe

In [1754]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1755]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Norm'],
  [2, 'Feedr'],
  [3, 'PosN'],
  [4, 'Artery'],
  [5, 'RRAe'],
  [6, 'RRNn'],
  [7, 'RRAn'],
  [8, 'PosA'],
  [9, 'RRNe']]}

In [1756]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Norm': 1,
 'Feedr': 2,
 'PosN': 3,
 'Artery': 4,
 'RRAe': 5,
 'RRNn': 6,
 'RRAn': 7,
 'PosA': 8,
 'RRNe': 9}

In [1757]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Diccionario `Condition2`

In [1758]:
column = 'Condition2'

In [1759]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0    Norm
1  Artery
2    RRNn
3   Feedr
4    PosN

In [1760]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1761]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1762]:
grouped.shape

(8, 2)

In [1763]:
grouped['index'] += 1
grouped

index     Key
0      1    Norm
1      2  Artery
2      3    RRNn
3      4   Feedr
4      5    PosN
5      6    PosA
6      7    RRAn
7      8    RRAe

In [1764]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1765]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Norm'],
  [2, 'Artery'],
  [3, 'RRNn'],
  [4, 'Feedr'],
  [5, 'PosN'],
  [6, 'PosA'],
  [7, 'RRAn'],
  [8, 'RRAe']]}

In [1766]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Norm': 1,
 'Artery': 2,
 'RRNn': 3,
 'Feedr': 4,
 'PosN': 5,
 'PosA': 6,
 'RRAn': 7,
 'RRAe': 8}

In [1767]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

## Diccionario `BldgType`

In [1768]:
column = 'BldgType'

In [1769]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0    1Fam
1  2fmCon
2  Duplex
3  TwnhsE
4   Twnhs

In [1770]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1771]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1772]:
grouped.shape

(5, 2)

In [1773]:
grouped['index'] += 1
grouped

index     Key
0      1    1Fam
1      2  2fmCon
2      3  Duplex
3      4  TwnhsE
4      5   Twnhs

In [1774]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1775]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, '1Fam'],
  [2, '2fmCon'],
  [3, 'Duplex'],
  [4, 'TwnhsE'],
  [5, 'Twnhs']]}

In [1776]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'1Fam': 1, '2fmCon': 2, 'Duplex': 3, 'TwnhsE': 4, 'Twnhs': 5}

In [1777]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `HouseStyle`

In [1778]:
column = 'HouseStyle'

In [1779]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  2Story
1  1Story
2  1.5Fin
3  1.5Unf
4  SFoyer

In [1780]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1781]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1782]:
grouped.shape

(8, 2)

In [1783]:
grouped['index'] += 1
grouped

index     Key
0      1  2Story
1      2  1Story
2      3  1.5Fin
3      4  1.5Unf
4      5  SFoyer
5      6    SLvl
6      7  2.5Unf
7      8  2.5Fin

In [1784]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1785]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, '2Story'],
  [2, '1Story'],
  [3, '1.5Fin'],
  [4, '1.5Unf'],
  [5, 'SFoyer'],
  [6, 'SLvl'],
  [7, '2.5Unf'],
  [8, '2.5Fin']]}

In [1786]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'2Story': 1,
 '1Story': 2,
 '1.5Fin': 3,
 '1.5Unf': 4,
 'SFoyer': 5,
 'SLvl': 6,
 '2.5Unf': 7,
 '2.5Fin': 8}

In [1787]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

## Diccionario `RoofStyle`

In [1788]:
column = 'RoofStyle'

In [1789]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0    Gable
1      Hip
2  Gambrel
3  Mansard
4     Flat

In [1790]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1791]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1792]:
grouped.shape

(6, 2)

In [1793]:
grouped['index'] += 1
grouped

index      Key
0      1    Gable
1      2      Hip
2      3  Gambrel
3      4  Mansard
4      5     Flat
5      6     Shed

In [1794]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1795]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Gable'],
  [2, 'Hip'],
  [3, 'Gambrel'],
  [4, 'Mansard'],
  [5, 'Flat'],
  [6, 'Shed']]}

In [1796]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Gable': 1, 'Hip': 2, 'Gambrel': 3, 'Mansard': 4, 'Flat': 5, 'Shed': 6}

In [1797]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6])

## Diccionario `RoofMatl`

In [1798]:
column = 'RoofMatl'

In [1799]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  CompShg
1  WdShngl
2    Metal
3  WdShake
4  Membran

In [1800]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1801]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1802]:
grouped.shape

(8, 2)

In [1803]:
grouped['index'] += 1
grouped

index      Key
0      1  CompShg
1      2  WdShngl
2      3    Metal
3      4  WdShake
4      5  Membran
5      6  Tar&Grv
6      7     Roll
7      8  ClyTile

In [1804]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1805]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'CompShg'],
  [2, 'WdShngl'],
  [3, 'Metal'],
  [4, 'WdShake'],
  [5, 'Membran'],
  [6, 'Tar&Grv'],
  [7, 'Roll'],
  [8, 'ClyTile']]}

In [1806]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'CompShg': 1,
 'WdShngl': 2,
 'Metal': 3,
 'WdShake': 4,
 'Membran': 5,
 'Tar&Grv': 6,
 'Roll': 7,
 'ClyTile': 8}

In [1807]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7, 8])

## Diccionario `Exterior1st`

In [1808]:
column = 'Exterior1st'

In [1809]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  VinylSd
1  MetalSd
2  Wd Sdng
3  HdBoard
4  BrkFace

In [1810]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1811]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1812]:
grouped.shape

(15, 2)

In [1813]:
grouped['index'] += 1
grouped

index      Key
0       1  VinylSd
1       2  MetalSd
2       3  Wd Sdng
3       4  HdBoard
4       5  BrkFace
5       6  WdShing
6       7  CemntBd
7       8  Plywood
8       9  AsbShng
9      10   Stucco
10     11  BrkComm
11     12  AsphShn
12     13    Stone
13     14  ImStucc
14     15   CBlock

In [1814]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1815]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'VinylSd'],
  [2, 'MetalSd'],
  [3, 'Wd Sdng'],
  [4, 'HdBoard'],
  [5, 'BrkFace'],
  [6, 'WdShing'],
  [7, 'CemntBd'],
  [8, 'Plywood'],
  [9, 'AsbShng'],
  [10, 'Stucco'],
  [11, 'BrkComm'],
  [12, 'AsphShn'],
  [13, 'Stone'],
  [14, 'ImStucc'],
  [15, 'CBlock']]}

In [1816]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'VinylSd': 1,
 'MetalSd': 2,
 'Wd Sdng': 3,
 'HdBoard': 4,
 'BrkFace': 5,
 'WdShing': 6,
 'CemntBd': 7,
 'Plywood': 8,
 'AsbShng': 9,
 'Stucco': 10,
 'BrkComm': 11,
 'AsphShn': 12,
 'Stone': 13,
 'ImStucc': 14,
 'CBlock': 15}

In [1817]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Diccionario `Exterior2nd`

In [1818]:
column = 'Exterior2nd'

In [1819]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  VinylSd
1  MetalSd
2  Wd Shng
3  HdBoard
4  Plywood

In [1820]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1821]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1822]:
grouped.shape

(16, 2)

In [1823]:
grouped['index'] += 1
grouped

index      Key
0       1  VinylSd
1       2  MetalSd
2       3  Wd Shng
3       4  HdBoard
4       5  Plywood
5       6  Wd Sdng
6       7  CmentBd
7       8  BrkFace
8       9   Stucco
9      10  AsbShng
10     11  Brk Cmn
11     12  ImStucc
12     13  AsphShn
13     14    Stone
14     15    Other
15     16   CBlock

In [1824]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1825]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'VinylSd'],
  [2, 'MetalSd'],
  [3, 'Wd Shng'],
  [4, 'HdBoard'],
  [5, 'Plywood'],
  [6, 'Wd Sdng'],
  [7, 'CmentBd'],
  [8, 'BrkFace'],
  [9, 'Stucco'],
  [10, 'AsbShng'],
  [11, 'Brk Cmn'],
  [12, 'ImStucc'],
  [13, 'AsphShn'],
  [14, 'Stone'],
  [15, 'Other'],
  [16, 'CBlock']]}

In [1826]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'VinylSd': 1,
 'MetalSd': 2,
 'Wd Shng': 3,
 'HdBoard': 4,
 'Plywood': 5,
 'Wd Sdng': 6,
 'CmentBd': 7,
 'BrkFace': 8,
 'Stucco': 9,
 'AsbShng': 10,
 'Brk Cmn': 11,
 'ImStucc': 12,
 'AsphShn': 13,
 'Stone': 14,
 'Other': 15,
 'CBlock': 16}

In [1827]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Diccionario `MasVnrType`

In [1828]:
column = 'MasVnrType'

In [1829]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  BrkFace
1     None
2    Stone
3   BrkCmn

In [1830]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1831]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1832]:
grouped.shape

(4, 2)

In [1833]:
grouped['index'] += 1
grouped

index      Key
0      1  BrkFace
1      2     None
2      3    Stone
3      4   BrkCmn

In [1834]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1835]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'BrkFace'], [2, 'None'], [3, 'Stone'], [4, 'BrkCmn']]}

In [1836]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'BrkFace': 1, 'None': 2, 'Stone': 3, 'BrkCmn': 4}

In [1837]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4., nan])

## Diccionario `ExterQual`

In [1838]:
column = 'ExterQual'

In [1839]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Gd
1  TA
2  Ex
3  Fa

In [1840]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1841]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1842]:
grouped.shape

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/IPython/core/displayhook.py:271: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  'Flushing oldest {cull_count} entries.'.format(sz=sz, cull_count=cull_count))


(4, 2)

In [1843]:
grouped['index'] += 1
grouped

index Key
0      1  Gd
1      2  TA
2      3  Ex
3      4  Fa

In [1844]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1845]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Gd'], [2, 'TA'], [3, 'Ex'], [4, 'Fa']]}

In [1846]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}

In [1847]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `ExterCond`

In [1848]:
column = 'ExterCond'

In [1849]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Fa
3  Po
4  Ex

In [1850]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1851]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1852]:
grouped.shape

(5, 2)

In [1853]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Fa
3      4  Po
4      5  Ex

In [1854]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1855]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Fa'], [4, 'Po'], [5, 'Ex']]}

In [1856]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4, 'Ex': 5}

In [1857]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `Foundation`

In [1858]:
column = 'Foundation'

In [1859]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   PConc
1  CBlock
2  BrkTil
3    Wood
4    Slab

In [1860]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1861]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1862]:
grouped.shape

(6, 2)

In [1863]:
grouped['index'] += 1
grouped

index     Key
0      1   PConc
1      2  CBlock
2      3  BrkTil
3      4    Wood
4      5    Slab
5      6   Stone

In [1864]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1865]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'PConc'],
  [2, 'CBlock'],
  [3, 'BrkTil'],
  [4, 'Wood'],
  [5, 'Slab'],
  [6, 'Stone']]}

In [1866]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'PConc': 1, 'CBlock': 2, 'BrkTil': 3, 'Wood': 4, 'Slab': 5, 'Stone': 6}

In [1867]:
df_copy[column] = df_copy[column].replace(dict__)
df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6])

## Diccionario `BsmtQual`

In [1868]:
column = 'BsmtQual'

In [1869]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Gd
1  TA
2  Ex
3  Fa

In [1870]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1871]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1872]:
grouped.shape

(4, 2)

In [1873]:
grouped['index'] += 1
grouped

index Key
0      1  Gd
1      2  TA
2      3  Ex
3      4  Fa

In [1874]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1875]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Gd'], [2, 'TA'], [3, 'Ex'], [4, 'Fa']]}

In [1876]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}

In [1877]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3., nan,  4.])

## Diccionario `BsmtCond`

In [1878]:
column = 'BsmtCond'

In [1879]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Fa
3  Po

In [1880]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1881]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1882]:
grouped.shape

(4, 2)

In [1883]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Fa
3      4  Po

In [1884]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1885]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Fa'], [4, 'Po']]}

In [1886]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4}

In [1887]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2., nan,  3.,  4.])

## Diccionario `BsmtExposure`

In [1888]:
column = 'BsmtExposure'

In [1889]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  No
1  Gd
2  Mn
3  Av

In [1890]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1891]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1892]:
grouped.shape

(4, 2)

In [1893]:
grouped['index'] += 1
grouped

index Key
0      1  No
1      2  Gd
2      3  Mn
3      4  Av

In [1894]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1895]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'No'], [2, 'Gd'], [3, 'Mn'], [4, 'Av']]}

In [1896]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'No': 1, 'Gd': 2, 'Mn': 3, 'Av': 4}

In [1897]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4., nan])

## Diccionario `BsmtFinType1`

In [1898]:
column = 'BsmtFinType1'

In [1899]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  GLQ
1  ALQ
2  Unf
3  Rec
4  BLQ

In [1900]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1901]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1902]:
grouped.shape

(6, 2)

In [1903]:
grouped['index'] += 1
grouped

index  Key
0      1  GLQ
1      2  ALQ
2      3  Unf
3      4  Rec
4      5  BLQ
5      6  LwQ

In [1904]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1905]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'GLQ'],
  [2, 'ALQ'],
  [3, 'Unf'],
  [4, 'Rec'],
  [5, 'BLQ'],
  [6, 'LwQ']]}

In [1906]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'GLQ': 1, 'ALQ': 2, 'Unf': 3, 'Rec': 4, 'BLQ': 5, 'LwQ': 6}

In [1907]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5., nan,  6.])

## Diccionario `BsmtFinType2`

In [1908]:
column = 'BsmtFinType2'

In [1909]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Unf
1  BLQ
2  ALQ
3  Rec
4  LwQ

In [1910]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1911]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1912]:
grouped.shape

(6, 2)

In [1913]:
grouped['index'] += 1
grouped

index  Key
0      1  Unf
1      2  BLQ
2      3  ALQ
3      4  Rec
4      5  LwQ
5      6  GLQ

In [1914]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1915]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Unf'],
  [2, 'BLQ'],
  [3, 'ALQ'],
  [4, 'Rec'],
  [5, 'LwQ'],
  [6, 'GLQ']]}

In [1916]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Unf': 1, 'BLQ': 2, 'ALQ': 3, 'Rec': 4, 'LwQ': 5, 'GLQ': 6}

In [1917]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2., nan,  3.,  4.,  5.,  6.])

## Diccionario `Heating`

In [1918]:
column = 'Heating'

In [1919]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  GasA
1  GasW
2  Grav
3  Wall
4  OthW

In [1920]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1921]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1922]:
grouped.shape

(6, 2)

In [1923]:
grouped['index'] += 1
grouped

index    Key
0      1   GasA
1      2   GasW
2      3   Grav
3      4   Wall
4      5   OthW
5      6  Floor

In [1924]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1925]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'GasA'],
  [2, 'GasW'],
  [3, 'Grav'],
  [4, 'Wall'],
  [5, 'OthW'],
  [6, 'Floor']]}

In [1926]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'GasA': 1, 'GasW': 2, 'Grav': 3, 'Wall': 4, 'OthW': 5, 'Floor': 6}

In [1927]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6])

## Diccionario `HeatingQC`

In [1928]:
column = 'HeatingQC'

In [1929]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Ex
1  Gd
2  TA
3  Fa
4  Po

In [1930]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1931]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1932]:
grouped.shape

(5, 2)

In [1933]:
grouped['index'] += 1
grouped

index Key
0      1  Ex
1      2  Gd
2      3  TA
3      4  Fa
4      5  Po

In [1934]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1935]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Ex'], [2, 'Gd'], [3, 'TA'], [4, 'Fa'], [5, 'Po']]}

In [1936]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Ex': 1, 'Gd': 2, 'TA': 3, 'Fa': 4, 'Po': 5}

In [1937]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5])

## Diccionario `CentralAir`

In [1938]:
column = 'CentralAir'

In [1939]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Y
1  N

In [1940]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1941]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1942]:
grouped.shape

(2, 2)

In [1943]:
grouped['index'] += 1
grouped

index Key
0      1   Y
1      2   N

In [1944]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1945]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Y'], [2, 'N']]}

In [1946]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Y': 1, 'N': 2}

In [1947]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2])

## Diccionario `Electrical`

In [1948]:
column = 'Electrical'

In [1949]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  SBrkr
1  FuseF
2  FuseA
3  FuseP
4    Mix

In [1950]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1951]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1952]:
grouped.shape

(5, 2)

In [1953]:
grouped['index'] += 1
grouped

index    Key
0      1  SBrkr
1      2  FuseF
2      3  FuseA
3      4  FuseP
4      5    Mix

In [1954]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1955]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'SBrkr'], [2, 'FuseF'], [3, 'FuseA'], [4, 'FuseP'], [5, 'Mix']]}

In [1956]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'SBrkr': 1, 'FuseF': 2, 'FuseA': 3, 'FuseP': 4, 'Mix': 5}

In [1957]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5., nan])

## Diccionario `KitchenQual`

In [1958]:
column = 'KitchenQual'

In [1959]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Gd
1  TA
2  Ex
3  Fa

In [1960]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1961]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1962]:
grouped.shape

(4, 2)

In [1963]:
grouped['index'] += 1
grouped

index Key
0      1  Gd
1      2  TA
2      3  Ex
3      4  Fa

In [1964]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1965]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Gd'], [2, 'TA'], [3, 'Ex'], [4, 'Fa']]}

In [1966]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Gd': 1, 'TA': 2, 'Ex': 3, 'Fa': 4}

In [1967]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4])

## Diccionario `Functional`

In [1968]:
column = 'Functional'

In [1969]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Typ
1  Min1
2  Maj1
3  Min2
4   Mod

In [1970]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1971]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1972]:
grouped.shape

(7, 2)

In [1973]:
grouped['index'] += 1
grouped

index   Key
0      1   Typ
1      2  Min1
2      3  Maj1
3      4  Min2
4      5   Mod
5      6  Maj2
6      7   Sev

In [1974]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1975]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Typ'],
  [2, 'Min1'],
  [3, 'Maj1'],
  [4, 'Min2'],
  [5, 'Mod'],
  [6, 'Maj2'],
  [7, 'Sev']]}

In [1976]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Typ': 1, 'Min1': 2, 'Maj1': 3, 'Min2': 4, 'Mod': 5, 'Maj2': 6, 'Sev': 7}

In [1977]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7])

## Diccionario `FireplaceQu`

In [1978]:
column = 'FireplaceQu'

In [1979]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Gd
2  Fa
3  Ex
4  Po

In [1980]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1981]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1982]:
grouped.shape

(5, 2)

In [1983]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Gd
2      3  Fa
3      4  Ex
4      5  Po

In [1984]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1985]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Gd'], [3, 'Fa'], [4, 'Ex'], [5, 'Po']]}

In [1986]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Gd': 2, 'Fa': 3, 'Ex': 4, 'Po': 5}

In [1987]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([nan,  1.,  2.,  3.,  4.,  5.])

## Diccionario `GarageType`

In [1988]:
column = 'GarageType'

In [1989]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Attchd
1   Detchd
2  BuiltIn
3  CarPort
4  Basment

In [1990]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [1991]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [1992]:
grouped.shape

(6, 2)

In [1993]:
grouped['index'] += 1
grouped

index      Key
0      1   Attchd
1      2   Detchd
2      3  BuiltIn
3      4  CarPort
4      5  Basment
5      6   2Types

In [1994]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [1995]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Attchd'],
  [2, 'Detchd'],
  [3, 'BuiltIn'],
  [4, 'CarPort'],
  [5, 'Basment'],
  [6, '2Types']]}

In [1996]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Attchd': 1,
 'Detchd': 2,
 'BuiltIn': 3,
 'CarPort': 4,
 'Basment': 5,
 '2Types': 6}

In [1997]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4., nan,  5.,  6.])

## Diccionario `GarageFinish`

In [1998]:
column = 'GarageFinish'

In [1999]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  RFn
1  Unf
2  Fin

In [2000]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2001]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2002]:
grouped.shape

(3, 2)

In [2003]:
grouped['index'] += 1
grouped

index  Key
0      1  RFn
1      2  Unf
2      3  Fin

In [2004]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2005]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'RFn'], [2, 'Unf'], [3, 'Fin']]}

In [2006]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'RFn': 1, 'Unf': 2, 'Fin': 3}

In [2007]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3., nan])

## Diccionario `GarageQual`

In [2008]:
column = 'GarageQual'

In [2009]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Fa
2  Gd
3  Ex
4  Po

In [2010]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2011]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2012]:
grouped.shape

(5, 2)

In [2013]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Fa
2      3  Gd
3      4  Ex
4      5  Po

In [2014]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2015]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Fa'], [3, 'Gd'], [4, 'Ex'], [5, 'Po']]}

In [2016]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Fa': 2, 'Gd': 3, 'Ex': 4, 'Po': 5}

In [2017]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3., nan,  4.,  5.])

## Diccionario `GarageCond`

In [2018]:
column = 'GarageCond'

In [2019]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  TA
1  Fa
2  Gd
3  Po
4  Ex

In [2020]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2021]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2022]:
grouped.shape

(5, 2)

In [2023]:
grouped['index'] += 1
grouped

index Key
0      1  TA
1      2  Fa
2      3  Gd
3      4  Po
4      5  Ex

In [2024]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2025]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'TA'], [2, 'Fa'], [3, 'Gd'], [4, 'Po'], [5, 'Ex']]}

In [2026]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'TA': 1, 'Fa': 2, 'Gd': 3, 'Po': 4, 'Ex': 5}

In [2027]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2., nan,  3.,  4.,  5.])

## Diccionario `GarageYrBlt`

In [2028]:
column = 'GarageYrBlt'

In [2029]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped = grouped.astype('int64')
grouped.head()

0
0  2003
1  1976
2  2001
3  1998
4  2000

In [2030]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2031]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2032]:
grouped.shape

(97, 2)

In [2033]:
grouped['index'] += 1
grouped

index   Key
0       1  2003
1       2  1976
2       3  2001
3       4  1998
4       5  2000
5       6  1993
6       7  2004
7       8  1973
8       9  1931
9      10  1939
10     11  1965
11     12  2005
12     13  1962
13     14  2006
14     15  1960
15     16  1991
16     17  1970
17     18  1967
18     19  1958
19     20  1930
20     21  2002
21     22  1968
22     23  2007
23     24  2008
24     25  1957
25     26  1920
26     27  1966
27     28  1959
28     29  1995
29     30  1954
..    ...   ...
67     68  1972
68     69  1918
69     70  1980
70     71  1924
71     72  1996
72     73  1940
73     74  1949
74     75  1994
75     76  1910
76     77  1978
77     78  1982
78     79  1992
79     80  1925
80     81  1941
81     82  2010
82     83  1927
83     84  1947
84     85  1937
85     86  1942
86     87  1938
87     88  1952
88     89  1928
89     90  1922
90     91  1934
91     92  1906
92     93  1914
93     94  1946
94     95  1908
95     96  1929
96     97  1933

[97 rows x 2 columns]

In [2034]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2035]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 2003],
  [2, 1976],
  [3, 2001],
  [4, 1998],
  [5, 2000],
  [6, 1993],
  [7, 2004],
  [8, 1973],
  [9, 1931],
  [10, 1939],
  [11, 1965],
  [12, 2005],
  [13, 1962],
  [14, 2006],
  [15, 1960],
  [16, 1991],
  [17, 1970],
  [18, 1967],
  [19, 1958],
  [20, 1930],
  [21, 2002],
  [22, 1968],
  [23, 2007],
  [24, 2008],
  [25, 1957],
  [26, 1920],
  [27, 1966],
  [28, 1959],
  [29, 1995],
  [30, 1954],
  [31, 1953],
  [32, 1983],
  [33, 1977],
  [34, 1997],
  [35, 1985],
  [36, 1963],
  [37, 1981],
  [38, 1964],
  [39, 1999],
  [40, 1935],
  [41, 1990],
  [42, 1945],
  [43, 1987],
  [44, 1989],
  [45, 1915],
  [46, 1956],
  [47, 1948],
  [48, 1974],
  [49, 2009],
  [50, 1950],
  [51, 1961],
  [52, 1921],
  [53, 1900],
  [54, 1979],
  [55, 1951],
  [56, 1969],
  [57, 1936],
  [58, 1975],
  [59, 1971],
  [60, 1923],
  [61, 1984],
  [62, 1926],
  [63, 1955],
  [64, 1986],
  [65, 1988],
  [66, 1916],
  [67, 1932],
  [68, 1972],
  [69, 1918],
  [70, 1980],
  [71, 1924],
  [72, 

In [2036]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{2003: 1,
 1976: 2,
 2001: 3,
 1998: 4,
 2000: 5,
 1993: 6,
 2004: 7,
 1973: 8,
 1931: 9,
 1939: 10,
 1965: 11,
 2005: 12,
 1962: 13,
 2006: 14,
 1960: 15,
 1991: 16,
 1970: 17,
 1967: 18,
 1958: 19,
 1930: 20,
 2002: 21,
 1968: 22,
 2007: 23,
 2008: 24,
 1957: 25,
 1920: 26,
 1966: 27,
 1959: 28,
 1995: 29,
 1954: 30,
 1953: 31,
 1983: 32,
 1977: 33,
 1997: 34,
 1985: 35,
 1963: 36,
 1981: 37,
 1964: 38,
 1999: 39,
 1935: 40,
 1990: 41,
 1945: 42,
 1987: 43,
 1989: 44,
 1915: 45,
 1956: 46,
 1948: 47,
 1974: 48,
 2009: 49,
 1950: 50,
 1961: 51,
 1921: 52,
 1900: 53,
 1979: 54,
 1951: 55,
 1969: 56,
 1936: 57,
 1975: 58,
 1971: 59,
 1923: 60,
 1984: 61,
 1926: 62,
 1955: 63,
 1986: 64,
 1988: 65,
 1916: 66,
 1932: 67,
 1972: 68,
 1918: 69,
 1980: 70,
 1924: 71,
 1996: 72,
 1940: 73,
 1949: 74,
 1994: 75,
 1910: 76,
 1978: 77,
 1982: 78,
 1992: 79,
 1925: 80,
 1941: 81,
 2010: 82,
 1927: 83,
 1947: 84,
 1937: 85,
 1942: 86,
 1938: 87,
 1952: 88,
 1928: 89,
 1922: 90,
 1934: 91,
 1906: 9

In [2037]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., nan, 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97.])

## Diccionario `PavedDrive`

In [2038]:
column = 'PavedDrive'

In [2039]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0  Y
1  N
2  P

In [2040]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2041]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2042]:
grouped.shape

(3, 2)

In [2043]:
grouped['index'] += 1
grouped

index Key
0      1   Y
1      2   N
2      3   P

In [2044]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2045]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Y'], [2, 'N'], [3, 'P']]}

In [2046]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Y': 1, 'N': 2, 'P': 3}

In [2047]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3])

## Diccionario `SaleType`

In [2048]:
column = 'SaleType'

In [2049]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0     WD
1    New
2    COD
3  ConLD
4  ConLI

In [2050]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2051]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2052]:
grouped.shape

(9, 2)

In [2053]:
grouped['index'] += 1
grouped

index    Key
0      1     WD
1      2    New
2      3    COD
3      4  ConLD
4      5  ConLI
5      6    CWD
6      7  ConLw
7      8    Con
8      9    Oth

In [2054]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

dict_keys(['index', 'columns', 'data'])

In [2055]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'WD'],
  [2, 'New'],
  [3, 'COD'],
  [4, 'ConLD'],
  [5, 'ConLI'],
  [6, 'CWD'],
  [7, 'ConLw'],
  [8, 'Con'],
  [9, 'Oth']]}

In [2056]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'WD': 1,
 'New': 2,
 'COD': 3,
 'ConLD': 4,
 'ConLI': 5,
 'CWD': 6,
 'ConLw': 7,
 'Con': 8,
 'Oth': 9}

In [2057]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Diccionario `SaleCondition`

In [2058]:
column = 'SaleCondition'

In [2059]:
grouped = pd.DataFrame(df_copy[column].dropna().unique())
grouped.head()

0
0   Normal
1  Abnorml
2  Partial
3  AdjLand
4   Alloca

In [2060]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['index', 0], dtype='object')

In [2061]:
grouped.rename(columns={0: 'Key'}, inplace=True)
grouped.columns

Index(['index', 'Key'], dtype='object')

In [2062]:
grouped.shape

(6, 2)

In [2063]:
grouped['index'] += 1
grouped

index      Key
0      1   Normal
1      2  Abnorml
2      3  Partial
3      4  AdjLand
4      5   Alloca
5      6   Family

In [2064]:
dict_ = grouped.to_dict(orient='split')
dict_.keys()

/Users/jacoboleon/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/IPython/core/displayhook.py:271: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  'Flushing oldest {cull_count} entries.'.format(sz=sz, cull_count=cull_count))


dict_keys(['index', 'columns', 'data'])

In [2065]:
dict_.pop('index')
dict_.pop('columns')
dict_

{'data': [[1, 'Normal'],
  [2, 'Abnorml'],
  [3, 'Partial'],
  [4, 'AdjLand'],
  [5, 'Alloca'],
  [6, 'Family']]}

In [2066]:
dict__ = {}

for line in dict_['data']:
    #print(line[1], ' : ', line[0])
    dict__[line[1]] = line[0]

dict__

{'Normal': 1,
 'Abnorml': 2,
 'Partial': 3,
 'AdjLand': 4,
 'Alloca': 5,
 'Family': 6}

In [2067]:
df_copy[column] = df_copy[column].replace(dict__)
#df_copy[column] = df_copy[column].astype('int64')
df_copy[column].unique()

array([1, 2, 3, 4, 5, 6])

In [2068]:
for line in df_copy.columns:
    print(line, ' : ', df_copy[line].unique(), '\n')

Id  :  [   1    2    3 ... 1458 1459 1460] 

MSSubClass  :  [ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40] 

MSZoning  :  [1 2 3 4 5] 

LotFrontage  :  [ 65.  80.  68.  60.  84.  85.  75.  nan  51.  50.  70.  91.  72.  66.
 101.  57.  44. 110.  98.  47. 108. 112.  74. 115.  61.  48.  33.  52.
 100.  24.  89.  63.  76.  81.  95.  69.  21.  32.  78. 121. 122.  40.
 105.  73.  77.  64.  94.  34.  90.  55.  88.  82.  71. 120. 107.  92.
 134.  62.  86. 141.  97.  54.  41.  79. 174.  99.  67.  83.  43. 103.
  93.  30. 129. 140.  35.  37. 118.  87. 116. 150. 111.  49.  96.  59.
  36.  56. 102.  58.  38. 109. 130.  53. 137.  45. 106. 104.  42.  39.
 144. 114. 128. 149. 313. 168. 182. 138. 160. 152. 124. 153.  46.] 

LotArea  :  [ 8450  9600 11250 ... 17217 13175  9717] 

Street  :  [1 2] 

Alley  :  [nan 'Grvl' 'Pave'] 

LotShape  :  [1 2 3 4] 

LandContour  :  [1 2 3 4] 

Utilities  :  [1 2] 

LotConfig  :  [1 2 3 4 5] 

LandSlope  :  [1 2 3] 

Neighborhood  :  [ 1  2  3  4  5 

In [2069]:
import math
print(math.nan)

nan


In [2070]:
import numpy as np
np.NaN

nan

## NaN

In [2071]:
df_copy.fillna(value=-1, inplace=True)

In [2072]:
n = df_copy.columns.values.tolist()
m = round(df_copy.shape[0]*.80)

l = []
for i in n:
    print(i)
    if df_copy[i].value_counts().get(-1) != None:
#        print(m, " < ", df_copy[i].value_counts().get(-1))
        if m < df_copy[i].value_counts().get(-1):
            print(i)
            l.append(i)
            df_copy.drop(labels=i, axis=1, inplace=True)

Id
MSSubClass
MSZoning
LotFrontage
LotArea
Street
Alley
Alley
LotShape
LandContour
Utilities
LotConfig
LandSlope
Neighborhood
Condition1
Condition2
BldgType
HouseStyle
OverallQual
OverallCond
YearBuilt
YearRemodAdd
RoofStyle
RoofMatl
Exterior1st
Exterior2nd
MasVnrType
MasVnrArea
ExterQual
ExterCond
Foundation
BsmtQual
BsmtCond
BsmtExposure
BsmtFinType1
BsmtFinSF1
BsmtFinType2
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
Heating
HeatingQC
CentralAir
Electrical
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
KitchenQual
TotRmsAbvGrd
Functional
Fireplaces
FireplaceQu
GarageType
GarageYrBlt
GarageFinish
GarageCars
GarageArea
GarageQual
GarageCond
PavedDrive
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
PoolQC
PoolQC
Fence
Fence
MiscFeature
MiscFeature
MiscVal
MoSold
YrSold
SaleType
SaleCondition
SalePrice


In [2073]:
df_copy.replace(to_replace= -1, value=np.NaN, inplace=True)

In [2074]:
df_copy.head()

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  \
0   1          60         1         65.0     8450       1         1   
1   2          20         1         80.0     9600       1         1   
2   3          60         1         68.0    11250       1         2   
3   4          70         1         60.0     9550       1         2   
4   5          60         1         84.0    14260       1         2   

   LandContour  Utilities  LotConfig    ...      EnclosedPorch  3SsnPorch  \
0            1          1          1    ...                  0          0   
1            1          1          2    ...                  0          0   
2            1          1          1    ...                  0          0   
3            1          1          3    ...                272          0   
4            1          1          2    ...                  0          0   

   ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  SaleCondition  \
0            0         0        0       2    2008         1              1   
1            0         0        0       5    2007         1              1   
2            0         0        0       9    2008         1              1   
3            0         0        0       2    2006         1              2   
4            0         0        0      12    2008         1              1   

   SalePrice  
0     208500  
1     181500  
2     223500  
3     140000  
4     250000  

[5 rows x 77 columns]

In [2075]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null int64
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null int64
LotShape         1460 non-null int64
LandContour      1460 non-null int64
Utilities        1460 non-null int64
LotConfig        1460 non-null int64
LandSlope        1460 non-null int64
Neighborhood     1460 non-null int64
Condition1       1460 non-null int64
Condition2       1460 non-null int64
BldgType         1460 non-null int64
HouseStyle       1460 non-null int64
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null int64
RoofMatl         1460 non-null int64
Exterior1st      1460 non-null int64
Exterior2nd      1460 non-null int64
Mas

In [2076]:
df_copy.to_csv('train_clean.csv')